# ?????? ??
spring:
  application:
    name: react-practice

  # MySQL ?????? ??
  datasource:
    url: jdbc:mysql://localhost:3306/onboard
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate
  jpa:
    hibernate:
      ddl-auto: update  # Hibernate? DB ???? ???? ??/??????? ??
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

# JWT ?? ??
jwt:
  secret:
    key: ${JWT_SECRET_KEY}